<template>
  <div class="position-relative min-height-10vh my-5">
    <div class="v-msg display-1">{{$t('global.commons.waiting_for_payment')}}</div>
  </div>
</template>

<script>
import { Language } from "@core/enums/language/Language";

export default {
  name: "SPaymentMercadopago",

  props: {
    publicKey: {
      require: true,
      type: String,
    },
    preferenceId: {
      /*Unique ID generated by Mercadopago*/ require: true,
      type: String,
    },
    currency: {
      require: true,
      type: String,
    },
  },
  data: () => ({}),
  computed: {
    locale() {
      if (this.getCurrentLanguage().code === Language.en.code) return "en-US";

      if (this.currency === "ARS") return "es-AR";
      else if (this.currency === "BRL") return "pt-BR";
      else if (this.currency === "CLP") return "es-CL";
      else if (this.currency === "COP") return "es-CO";
      else if (this.currency === "MXN") return "es-MX";
      else if (this.currency === "PEN") return "es-PE";
      else if (this.currency === "UYU") return "es-UY";

      return "en-US";
    },
  },

  mounted() {
    this.initilize();
  },

  methods: {
    /**
     * ――――――――――――――――――――― Initialize ――――――――――――――――――――
     */

    initilize() {
      const mp = new MercadoPago(this.publicKey, {
        locale: this.locale,
      });

      mp.checkout({
        preference: {
          id: this.preferenceId,
        },
        autoOpen: true, // Allow the Checkout Pro to open automatically

        theme: {
          elementsColor: this.SaminColorLight,
          headerColor: this.SaminColorDarkDeep,
        },
      });
    },
  },
};
</script>

<style scoped lang="scss">
.v-msg {
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  background-color: #fff;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 8px;
  z-index: 999;
}
</style>
