<!--
  - Copyright (c) 2023. Selldone® Business OS™
  -
  - Author: M.Pajuhaan
  - Web: https://selldone.com
  - ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  -
  - All rights reserved. In the weave of time, where traditions and innovations intermingle, this content was crafted.
  - From the essence of thought, through the corridors of creativity, each word, and sentiment has been molded.
  - Not just to exist, but to inspire. Like an artist's stroke or a sculptor's chisel, every nuance is deliberate.
  - Our journey is not just about reaching a destination, but about creating a masterpiece.
  - Tread carefully, for you're treading on dreams.
  -->

<template>
  <div class="mb-4">
    <v-expand-transition>
      <u-loading-progress v-if="busy"></u-loading-progress>
      <div v-else class="widget-box mb-5">
        <u-widget-header
          icon="barcode_reader"
          title="Barcode Scanner Config"
        ></u-widget-header>
        <v-list-subheader>
          You can connect compatible barcode scanners to your POS just by
          entering your WiFi info and scan the generated QR code by barcode
          scanner.
        </v-list-subheader>
        <v-text-field
          v-model="wifi_ssid"
          :label="$t('barcode_scanner.wifi_ssid')"
          :messages="$t('barcode_scanner.ssid_message')"
          class="my-5 english-field"
          prepend-inner-icon="wifi"
          variant="solo-inverted"
        ></v-text-field>

        <v-text-field
          v-model="wifi_pass"
          :label="$t('barcode_scanner.wifi_pass')"
          :messages="$t('barcode_scanner.message')"
          class="my-5 english-field"
          prepend-inner-icon="password"
          variant="solo-inverted"
        ></v-text-field>

        <u-qrcode
          v-if="qrcode_value"
          :options="{
            width: $vuetify.display.mdAndUp ? 420 : 250,
            color: { dark: '#000', light: '#fff' },
          }"
          :value="qrcode_value"
          class="d-block mx-auto my-5"
          style="max-width: 100%; border-radius: 12px"
        />

        <u-text-copy-box
          :value="secure_url"
          message="Secure URL! Do not share it with others."
          small-width-mode
        ></u-text-copy-box>
      </div>
    </v-expand-transition>

    <v-expansion-panels class="max-widget-width mx-auto text-start">
      <v-expansion-panel rounded="xl">
        <v-expansion-panel-title>
          <v-icon class="me-2">qr_code_scanner</v-icon>
          How to connect barcode scanner?
        </v-expansion-panel-title>
        <v-expansion-panel-text>
          <p class="mb-3">
            Selldone supports direct connections with compatible barcode
            scanners, eliminating the need for additional hardware or software
            (feature coming soon). For barcode scanners not directly compatible
            with Selldone, a straightforward piece of hardware is required to
            facilitate HTTP request transmissions. Moreover, you have the option
            to create applications capable of scanning QR codes, effectively
            turning any smartphone into a barcode scanner.
          </p>
          <h2 class="mt-5">Option 1. Convert your phone to barcode scanner</h2>
          <p>
            You can use your smartphone as a barcode scanner by installing a
            barcode scanner app. The app will scan the QR code generated by the
            POS and send the scanned data to the POS.
          </p>

          <p>
            Search for <b>Selldone barcode scanner</b> in Googleplay or
            Appstore.
          </p>

          <a
            class="ma-2 d-inline-block"
            href="https://play.google.com/store/apps/details?id=com.selldone.pos"
            target="_blank"
            title="Selldone POS Barcode Scanner"
            ><img
              :height="42"
              :src="require('../../../../assets/trademark/googleplay.png')"
          /></a>

          <h2 class="mt-5">Option 2. Integration Steps for Developers:</h2>
          <ol>
            <li class="my-2">
              <b>Secure URL Acquisition:</b> Initially, scan a QR code to obtain
              a secure URL in JSON format containing
              <code>{url, ssid, pass}</code>. The ssid and pass fields, which
              pertain to your WiFi network, are optional but helpful for easily
              connecting intermediary hardware to your local network.
            </li>
            <li class="my-2">
              <b>Send a GET Request:</b> Use the URL from Step 1 to send a GET
              request. This request will return a JSON response comprising
              <code>{success, token, url}</code>.
            </li>
            <li class="my-2">
              <b>Post Request with Barcode Data:</b> With the URL and token
              obtained, your barcode scanner must then send a POST request to
              the provided URL. This request should include the
              <code>token</code>, <code>sku</code>, and
              <code>quantity</code> within its body, aiming to add a specific
              quantity of an item to the cart. The response to this request will
              be detailed as
              <code
                >{success, product_id, variant_id, quantity, product,
                variant}</code
              >, confirming the transaction's success and providing relevant
              product information.
            </li>
          </ol>
        </v-expansion-panel-text>
      </v-expansion-panel>
    </v-expansion-panels>

    <v-btn
      class="absolute-top-end"
      icon
      prepend-icon="close"
      variant="text"
      @click="$emit('close')"
    >
      <v-icon>close</v-icon>
    </v-btn>
  </div>
</template>

<script lang="ts">
import { PosDeviceTypes } from "@selldone/core-js/enums/pos/PosDeviceTypes";
import UWidgetHeader from "../../../../ui/widget/header/UWidgetHeader.vue";
import UTextCopyBox from "../../../../ui/text/copy-box/UTextCopyBox.vue";

export default {
  name: "BPosDeviceBarcodeScanner",
  components: { UTextCopyBox, UWidgetHeader },
  emits: ["close", "add"],
  props: {
    shop: {
      type: Object,
      require: true,
    },
    deviceData: {},
  },

  data: () => ({
    busy: false,

    wifi_ssid: null,
    wifi_pass: null,
    secure_url: null, // Secure URL generated by server
  }),
  computed: {
    qrcode_value() {
      return JSON.stringify({
        ssid: this.wifi_ssid,
        pass: this.wifi_pass,
        url: this.secure_url,
      });
    },
  },

  watch: {
    deviceData(scanner_data) {
      // Listen on device connect signal:
      if (
        scanner_data.device &&
        scanner_data.device.connected &&
        scanner_data.device.type === PosDeviceTypes.Scanner.code
      ) {
        this.$emit("close");
        this.$emit("add", scanner_data.device);
      }
    },
  },

  created() {
    this.getSecureUrl();
  },

  methods: {
    getSecureUrl() {
      this.busy = true;

      axios
        .get(
          window.API.GET_CASH_REGISTER_SECURE_URL(
            this.shop.id,
            PosDeviceTypes.Scanner.code,
          ),
        )
        .then(({ data }) => {
          this.secure_url = data.url;
        })
        .catch((error) => {
          this.showLaravelError(error);
        })
        .finally(() => (this.busy = false));
    },
  },
};
</script>

<style lang="scss" scoped>
code {
  font-weight: bold;
}
</style>
