<!--
  - Copyright (c) 2023. Selldone® Business OS™
  -
  - Author: M.Pajuhaan
  - Web: https://selldone.com
  - ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  -
  - All rights reserved. In the weave of time, where traditions and innovations intermingle, this content was crafted.
  - From the essence of thought, through the corridors of creativity, each word, and sentiment has been molded.
  - Not just to exist, but to inspire. Like an artist's stroke or a sculptor's chisel, every nuance is deliberate.
  - Our journey is not just about reaching a destination, but about creating a masterpiece.
  - Tread carefully, for you're treading on dreams.
  -->

<template>
  <v-list class="border-between-vertical bg-transparent text-start">
    <v-list-item
      v-for="file in files"
      :key="file.id"
      :class="{ 'row-hover': canDownload(file), pen: !canDownload(file) }"
      @click="
        canDownload(file)
          ? file.download_link
            ? window.open(file.download_link, '_blank')
            : getBuyerFileUrl(file)
          : undefined
      "
    >
      <!--    v-bind="file.download_link ? { href: file.download_link } : undefined" -->
      <template v-slot:prepend>
        <v-avatar tile>
          <img :src="FileHelper.GetFileExtensionImage(file.name)" :alt="`File Format`" />
        </v-avatar>
      </template>

      <v-list-item-title class="text-subtitle-2 py-1 d-flex align-center">
        <div
          :title="file.name"
          class="flex-grow-1 single-line inline-block font-weight-black"
        >
          {{ file.name }}
        </div>

        <v-chip
          v-if="file.sample"
          class="mx-2"
          color="#009688"
          variant="flat"
          label
          size="small"
          style="min-width: 68px"
          >Sample
        </v-chip>
        <v-chip
          v-else
          class="mx-2"
          color="#673AB7"
          variant="flat"
          label
          size="small"
          style="min-width: 68px"
        >
          <v-icon size="small" start>diamond</v-icon>
          Paid
        </v-chip>
      </v-list-item-title>
      <v-list-item-subtitle>
        <v-btn
          v-if="file.download_link"
          :color="copied_items.includes(file.id) ? 'green' : 'primary'"
          size="small"
          title="Copy download link."
          variant="text"
          @click.stop="
            copyToClipboard(file.download_link);
            copied_items.add(file.id);
          "
        >
          <v-icon class="me-1" size="small"
            >{{ copied_items.includes(file.id) ? "check_circle" : "file_copy" }}
          </v-icon>
          {{ $t("global.commons.download_link") }}
        </v-btn>
      </v-list-item-subtitle>

      <v-list-item-action style="flex-basis: 50px">
        <div class="text-center english-field text-subtitle-2" dir="ltr">
          {{ numeralFormat(file.size * 1024, "0.[0] b") }}
        </div>

        <v-btn
          v-if="canDownload(file)"
          :loading="busy_get_file === file"
          color="#1976D2"
          icon
          title="Download"
        >
          <v-icon>cloud_download</v-icon>
        </v-btn>
      </v-list-item-action>
    </v-list-item>
  </v-list>
</template>

<script lang="ts">
import NotificationService from "@selldone/components-vue/plugins/notification/NotificationService.ts";

import { ShopOptionsHelper } from "@selldone/core-js/helper/shop/ShopOptionsHelper";
import AuthMixin from "@selldone/components-vue/mixin/auth/AuthMixin.ts";
import {FileHelper} from "@selldone/core-js/utils";


export default {
  name: "SShopProductFilesList",
  mixins: [AuthMixin ],

  props: {
    files: {
      required: true,
    },
    basket: {
      // For guest file purchase
      required: false,
    },

    purchased: {
      type: Boolean,
    },
  },

  computed: {
    FileHelper() {
      return FileHelper
    }
  },
  watch: {},

  data: function () {
    return {
      files_show: false,
      busy_get_file: null,

      copied_items: [],
    };
  },

  created() {},
  methods: {
    getBuyerFileUrl(file) {
      if (
        !this.USER() &&
        !ShopOptionsHelper.HasGuestCheckout(this.getShop()) /*🥶 Guest*/
      ) {
        return this.NeedLogin();
      }

      this.busy_get_file = file;

      axios
        .get(
          window.XAPI.GENERATE_DOWNLOAD_PRODUCT_FILE_TEMP_URL(
            this.shop_name,
            file.product_id,
            file.id,
          ),
          {
            params: {
              code: this.basket?.code /*🥶 Guest*/,

              /**
                   This property holds the signature from the URL query parameters.
                   The signature is a cryptographic hash that ensures the integrity and authenticity
                   of the URL, preventing tampering. It's typically generated by shop staff when creating
                   secure, time-limited URLs to display order details.
                   */

              signature: this.$route.query.signature,
              /**
                   This property holds the timestamp from the URL query parameters.
                   The timestamp indicates when the URL was created and is used to ensure the URL's validity
                   within a specific time frame. Like the signature, this is also generated by shop staff
                   when creating secure URLs to display order details.
                   */
              timestamp: this.$route.query.timestamp,

              basket_id: this.basket?.id,
            },
          },
        )
        .then(({ data }) => {
          if (!data.error) {
            let link = document.createElement("a");
            link.download = name;
            link.href = data.url;
            link.click();

            // Add link to file:
            file.download_link = data.url;
          } else {
            NotificationService.showErrorAlert(null, data.error_msg);
          }
        })
        .catch((error) => {
          NotificationService.showLaravelError(error);
        })
        .finally(() => {
          this.busy_get_file = null;
        });
    },
    canDownload(file) {
      return this.purchased || file.sample;
    },
  },
};
</script>

<style lang="scss" scoped>
/*
━━━━━━━━━━━━━━━━━━━━ 🎺 Variables ━━━━━━━━━━━━━━━━━━━━
 */
.s--shop-product-files-list {
}

/*
━━━━━━━━━━━━━━━━━━━━ 🪅 Classes ━━━━━━━━━━━━━━━━━━━━
 */
.s--shop-product-files-list {
}
</style>
