<!--
  - Copyright (c) 2023-2024. Selldone® Business OS™
  -
  - Author: M.Pajuhaan
  - Web: https://selldone.com
  - ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  -
  - All rights reserved. In the weave of time, where traditions and innovations intermingle, this content was crafted.
  - From the essence of thought, through the corridors of creativity, each word, and sentiment has been molded.
  - Not just to exist, but to inspire. Like an artist's stroke or a sculptor's chisel, every nuance is deliberate.
  - Our journey is not just about reaching a destination, but about creating a masterpiece.
  - Tread carefully, for you're treading on dreams.
  -->

<template xmlns:v-slot="http://www.w3.org/1999/XSL/Transform">
  <!-- █████████████████████ Chat Messages █████████████████████ -->

  <div>
    <div v-if="chat" class="widget-box -large mb-5">
      <u-widget-header
        :title="$t('global.commons.messages')"
        icon="3p"
      ></u-widget-header>
      <v-list-subheader>
        {{ $t("global.order_chat.customer.history.subtitle") }}
      </v-list-subheader>
      <s-order-chat-message
        v-for="(message, i) in chat"
        :key="i"
        :basket="basket"
        :message="message"
        class="my-2 c-bubble"
        has-delete
      >
      </s-order-chat-message>
    </div>

    <div class="widget-box -large mb-5">
      <u-widget-header
        :title="$t('global.actions.add_new_message')"
        icon="add_comment"
      ></u-widget-header>
      <v-list-subheader>
        {{ $t("global.order_chat.customer.new_message.subtitle") }}
      </v-list-subheader>

      <div class="d-flex align-center my-3">
        <v-avatar :size="32" class="avatar-gradient -thin -user me-2">
          <v-img v-if="USER_ID()" :src="getUserAvatar(USER_ID())" />
          <v-icon v-else>account_circle</v-icon>
        </v-avatar>
        <div class="flex-grow-1">
          <b>{{ user?.profile?.name?user.profile.name: user ? user.name : $t("global.commons.guest") }}</b>
          <small class="d-block">{{ $t("global.commons.now") }}</small>
        </div>
      </div>

      <v-textarea
        v-model="body_input"
        :counter="1024"
        :label="$t('global.commons.message')"
        auto-grow
        bg-color="#fafafa"
        flat
        rounded="xl"
        variant="solo-filled"
      ></v-textarea>

      <div class="widget-buttons">
        <v-btn
          :class="{ disabled: !body_input }"
          :disabled="!body_input"
          :loading="busy_add"
          color="primary"
          size="x-large"
          variant="elevated"
          @click="addChat"
        >
          {{ $t("global.actions.send") }}

          <v-icon end class="flip-rtl">send</v-icon>
        </v-btn>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import SOrderChatMessage from "../message/SOrderChatMessage.vue";

export default {
  name: "SOrderChatBox",

  components: {
    SOrderChatMessage,
  },
  inject: ["$shop"],
  props: {
    basket: {
      require: true,
      type: Object,
    },
  },

  data: () => ({
    busy_add: false,
    body_input: null,
  }),

  computed: {
    user() {
      return this.USER();
    },
    chat() {
      return this.basket.chat;
    },
  },

  watch: {},

  created() {},

  methods: {
    addChat() {
      this.busy_add = true;

      axios
        .post(
          window.XAPI.POST_CUSTOMER_BASKET_CHAT_ADD_MESSAGE(
            this.$shop.name,
            this.basket.id,
          ),
          {
            body: this.body_input,

            /**
                 This property holds the signature from the URL query parameters.
                 The signature is a cryptographic hash that ensures the integrity and authenticity
                 of the URL, preventing tampering. It's typically generated by shop staff when creating
                 secure, time-limited URLs to display order details.
                 */

            signature: this.$route.query.signature,
            /**
                 This property holds the timestamp from the URL query parameters.
                 The timestamp indicates when the URL was created and is used to ensure the URL's validity
                 within a specific time frame. Like the signature, this is also generated by shop staff
                 when creating secure URLs to display order details.
                 */
            timestamp: this.$route.query.timestamp,
          },
        )
        .then(({ data }) => {
          if (data.error) {
            this.showErrorAlert(null, data.error_msg);
          } else {
            this.body_input = null;
            this.basket.chat = data.chat;
            this.showSuccessAlert(null, "Message has been added successfully.");
          }
        })
        .catch((error) => {
          this.showLaravelError(error);
        })
        .finally(() => {
          this.busy_add = null;
        });
    },
  },
};
</script>

<style lang="scss" scoped>
.c-bubble {
  background-color: #fff;
  border-radius: 18px;
  text-align: start;
  padding: 8px 12px;
}
</style>
